"Name: T­íng qu©n thñ thµnh ID: 48 Script: \script\missions\newcitydefence\npc\cd_signnpc.lua DropFile: \settings\item\npcdroprate.ini Life: 100 NguHanh: 0 Kind: 3"
"Name: T­íng qu©n thñ thµnh ID: 48 Script: \script\missions\newcitydefence\npc\cd_signnpc.lua DropFile: \settings\item\npcdroprate.ini Life: 100 NguHanh: 0 Kind: 3"
"Name: Qu©n TèngXa phu ID: 393 Script: \script\missions\newcitydefence\npc\cd_transer.lua DropFile:  Life: 100 NguHanh: 1 Kind: 3"
"Name: C«ng Tr¹ng Quan ID: 373 Script: \script\global\npctinsu.lua DropFile:  Life: 100 NguHanh: 3 Kind: 3"
"Name: ÎäÁÖÃË´«ÈË ID: 308 Script: \script\global\Â·ÈË_ÎäÁÖÃË´«ÈË.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: ³µ·ò ID: 393 Script: \script\ÖÐÔ­ÄÏÇø\ÏåÑô\ÏåÑô\npc\ÏåÑô_æäÕ¾³µ·ò¶Ô»°.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: Hç Trî T©n Thñ ID: 1867 Script: \script\global\vanhungfc\nangcapngua\hotroday.lua DropFile:  Life: 100 NguHanh: 1 Kind: 3"
"Name: Hç Trî T©n Thñ ID: 1867 Script: \script\global\vanhungfc\nangcapngua\hotroday.lua DropFile:  Life: 100 NguHanh: 1 Kind: 3"
"Name: Tiªu Dao Tö   ID: 2533 Script: \script\global\tieudaotu.lua DropFile: \settings\item\npcdroprate.ini Life: 100 NguHanh: 4 Kind: 3"
"Name: ThÇn Tµi ID: 1528 Script: \script\global\general\npc_sukien_dieuphoi.lua DropFile: \settings\item\npcdroprate.ini Life: 100 NguHanh: 1 Kind: 3"
"Name: Tiªu Dao Tö   ID: 2537 Script: \script\global\tieudaotu.lua DropFile: \settings\item\npcdroprate.ini Life: 100 NguHanh: 4 Kind: 3"
"Name: Thiªn Hoµng Cöa hµng ID: 85 Script: \script\global\npc\thienhoangcuahang.lua DropFile: \settings\item\npcdroprate.ini Life: 100 NguHanh: 1 Kind: 3"
"Name: Thiªn Hoµng Cöa hµng ID: 85 Script: \script\global\npc\thienhoangcuahang.lua DropFile: \settings\item\npcdroprate.ini Life: 100 NguHanh: 1 Kind: 3"
"Name: ThÇn Tiªn Tû Tû ID: 1393 Script: \script\global\npchotrotanthu.lua DropFile:  Life: 100 NguHanh: 1 Kind: 3"
